/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EventModal: typeof import('./src/components/calendar/EventModal.vue')['default']
    IconMdiAccountGroupOutline: typeof import('~icons/mdi/account-group-outline')['default']
    IconMdiBellOutline: typeof import('~icons/mdi/bell-outline')['default']
    IconMdiCalendarMonthOutline: typeof import('~icons/mdi/calendar-month-outline')['default']
    IconMdiCalendarOutline: typeof import('~icons/mdi/calendar-outline')['default']
    IconMdiChatOutline: typeof import('~icons/mdi/chat-outline')['default']
    IconMdiClockTimeFourOutline: typeof import('~icons/mdi/clock-time-four-outline')['default']
    IconMdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    IconMdiFileDocumentOutline: typeof import('~icons/mdi/file-document-outline')['default']
    IconMdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    IconMdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    IconMdiInboxArrowDownOutline: typeof import('~icons/mdi/inbox-arrow-down-outline')['default']
    IconMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IconMdiPackageVariant: typeof import('~icons/mdi/package-variant')['default']
    IconMdiViewDashboardOutline: typeof import('~icons/mdi/view-dashboard-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Topbar: typeof import('./src/components/layout/Topbar.vue')['default']
  }
}
